# NAO faca commit deste arquivo com valores reais preenchidos.
# Pegue a License Key em: New Relic > (perfil) > API keys > Ingest - License
apiVersion: v1
kind: Secret
metadata:
  name: otel-collector-secrets
  namespace: monitoring
type: Opaque
stringData:
  NEW_RELIC_LICENSE_KEY: "300D416452C22F6E265D204B7DD16486BEFC879B602118C196602A17612ABAD9"